### PR TITLE
Benchmarks for TriMesh transforms

### PR DESCRIPTION
**Pull request by nirmal-suthar**

### CODE REVIEW

**Comment by nirmal-suthar** [comment]
bm_trimesh

**Comment by avik-pal** [comment]
Do you have any intuition why Kaolin's CPU benchmark is so noisy? You could try increasing the niters for benchmarking to reduce the variance (though it should not affect the min time)

**Comment by nirmal-suthar** [comment]
bm_trimesh

**Comment by avik-pal** [comment]
Hmm... Yeah it doesn't help!! Let's try and use some standard mesh. Just use an icosphere and plot the trend.

**Comment by nirmal-suthar** [comment]
> Hmm... Yeah it doesn't help!! Let's try and use some standard mesh. Just use an icosphere and plot the trend.

Can using `time` module be noisy, as benchmarks looks pretty smooth in gpu, which is not using this module?

**Comment by avik-pal** [comment]
It is possible, but again the pytorch people are also using a [similar script](https://github.com/pytorch/benchmark/blob/e645c888ff356609e991f4f4c53075a0cbbdd81b/timing/python/benchmarks/cpu_convnet_benchmark.py#L60-L75)

**Comment by nirmal-suthar** [comment]
I guess, I have figured out the problem. Cyclops CPU are already busy and while running cpu benchmark, htop shows all cpu as maxed out, which is why benchmarks are noisy [I have updated above plots]. I will run benchmarks script again once cyclops is free.

**Comment by nirmal-suthar** [comment]
I have updated TriMesh plot above, cyclops was mostly free while benchmarking.

**Comment by avik-pal** [comment]
Hmm... Interesting. So making it in place has zero effect on the performance... That doesn't seem right!

**Comment by nirmal-suthar** [comment]
Due to some reason chamfer distance in kaolin is not working on my setup, so would try fixing it today. This loss is written in cuda native, so not able to figure out exactly.

**Comment by avik-pal** [comment]
Interesting... If you cant fix it let me know. I have kaolin setup on a cluster. I will install julia and run the benchmarks. (And maybe post which exact scripts I need to run)

**Comment by nirmal-suthar** [comment]
Kaolin benchmarks were too noisy on cyclops, So I tried benchmarking on colab
bm_metrics_colab
bm_trimesh_colab

**Comment by nirmal-suthar** [comment]
@avik-pal Is build failing due to julia 1.3 is not compatible with GPUCompiler?
`ERROR: Unsatisfiable requirements detected for package GPUCompiler [61eb1bfa]:` 
Tests are passing locally on julia 1.4

**Comment by avik-pal** [comment]
@nirmal-suthar Could you try getting rid of the Manifest once?
It says `restricted to versions 0.5.5 by an explicit requirement, leaving only versions 0.5.5` but there is no restriction on the Project.toml

**Comment by avik-pal** [comment]
> chamfer_distance cpu kaolin was very slow to benchmark

True. I am happy that Flux3d can at least compute it on CPU. It is a very expensive operation and a general bottleneck for any 3d mesh-based work I have ever done. I would suggest putting a note that the Kaolin one is too slow to be benchmarked in a reasonable time.

We also need the timing for the forward and backward pass. So every plot in the grid should have 6 lines (forward, backward, total for both frameworks).

**Comment by avik-pal** [comment]
I also feel it makes sense for us to have a cuda kernel for chamfer distance given that the difference rn is somewhat big.

**Comment by nirmal-suthar** [comment]
The above benchmarks are on CUDA#master

**Comment by avik-pal** [comment]
Normalize is slow on master? I checked yesterday it was faster on my setup on cyclops.

**Comment by nirmal-suthar** [comment]
Current issues with chamfer distance in Flux3D is that for calculating nearest neighbours distances, we are computing a matrix multiplication (of size N1 x N2 x B) which is really space expensive operation for high no. of verts. But yes, it is able to match kaolin for average number of points.

**Comment by avik-pal** [comment]
I have never come across 2^14 vertices in practice. Most of my problems involved like 1000 vertices. So it is good that we can match the performance of a cuda kernel without writing one ourselves. I would suggest finishing the remaining benchmarks and open an issue for this and tackle it separately.

**Comment by nirmal-suthar** [comment]
> Normalize is slow on master? I checked yesterday it was faster on my setup on cyclops.

Benchmarks on cyclops (CUDA#master) were better than previous numbers. But I will check this again.

**Comment by nirmal-suthar** [comment]
bm_metrics

**Comment by nirmal-suthar** [comment]
@avik-pal I am not able to match normalize with kaolin on GPU. Can this be due to my Julia env? In my Julia env, CUDA version is 1.2.1

**Comment by avik-pal** [comment]
I think it might be some mistake from my end. Anyways the difference is not much

From the updated plots I feel we need to have the kernel for chamfer distance and an adjoint for that, It should allow us to beat the kaolin numbers. Even for laplacian loss we need that adjoint. Since these are for an unreasonably high number of vertices, let's not block this PR for that and handle it elsewhere.

**Comment by nirmal-suthar** [comment]
Posting some points before merging this PR:
- CUSPARSE is currently broken for Float32 and cusparse-matrix is taking lot greater time, so using Sparse for laplacian_loss even on gpu.
- Laplacian_loss in kaolin is slightly different from Flux3D, so for benchmarking in kaolin I am using a simple custom laplacian_loss which matched that of Flux3D.

**Comment by avik-pal** [comment]
In the benchmarks directory create a readme and mention these points.

Additionally if the cusparse issue is not known open an issue in cuda.jl

**Comment by nirmal-suthar** [comment]
There was an existing issue
CUDA.jl/issues/322

**Pull request merged**
